server:
  port: 80
  servlet:
    context-path: /excel
spring:
  datasource:
    url: jdbc:mysql://localhost:3306:ik
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
